#!/bin/sh -e

pkgname=fansi
debname=r-cran-fansi

if [ "$AUTOPKGTEST_TMP" = "" ] ; then
    AUTOPKGTEST_TMP=`mktemp -d /tmp/${debname}-test.XXXXXX`
    trap "rm -rf $AUTOPKGTEST_TMP" 0 INT QUIT ABRT PIPE TERM
fi
cd $AUTOPKGTEST_TMP
cp -a /usr/share/doc/$debname/tests/* $AUTOPKGTEST_TMP
gunzip -r *
for testfile in *.R; do
    echo "BEGIN TEST $testfile"
    LC_ALL=C R --no-save < $testfile
done

cat <<EOT
*********************************************************************
* Loading required package: unitizer                                *
* Warning message:                                                  *
* Cannot run tests without package 'unitizer'                       *
*                                                                   *
* r-cran-unitizer is in new - test should be enhanced once accepted *
*********************************************************************
EOT
